---
title: 'Collateral Value and Strategic Default: Evidence from Auto Loans'
author: "Dimuthu Ratnadiwakara"
date: "January, 2018"
output:
  html_document:
    css: bodycss.css
    fig_width: 8
    font-family: Helvetica,Arial,sans-serif;
    number_section: yes
    toc: yes
linestretch: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE,echo = FALSE, fig.align='center')
```

```{r data_clean}
rm(list=ls())
library(dplyr)
library(lubridate)
library(reshape2)
library(ggplot2)
library(lfe)
library(stargazer)
library(MatchIt)
library(data.table)
library(plyr)


completeFun <- function(data, desiredCols) {
  completeVec <- complete.cases(data[, desiredCols])
  return(data[completeVec, ])
}
    # lb_data <- read.csv(file="E:/auto_strategicdefault/Raw Data/lb_raw_cleaned.csv",stringsAsFactors = FALSE)
    # lb_data['make_model'] <- paste(lb_data$make,lb_data$model)
    # 
    # tw <- lb_data[lb_data$make=="BAJAJ"  & !is.na(lb_data$valuation_org),]
    # tw <- lb_data[lb_data$model %in% c("4 STROKE","2 STROKE","RE 205","RE 4S AUTORICKSHAW-SB","RE","RE205","BAJAJ-RE-4S","AR4S-UG",
    #                                "AUTO AR4S","BAJAJ AUTO","RE 4S AUTORICKSHAW - SV UG","AUTO RE 2 STROKE","AR RE200",
    #                                "BAJAJ 4 S"),]
    # tw['type'] = "threewheeler"
    # 
    # mb <- lb_data[lb_data$make_model %in% c("HONDA DIO","BAJAJ PULSAR 150 UG4.5","YAMAHA RAY ZR","T V S WEGO","BAJAJ CT 100 UG","BAJAJ PULSAR 135 LS","BAJAJ PULSAR 150 UG4.5-DTSI 4S","YAMAHA FZ-S","BAJAJ PULSAR 150","HERO PLEASURE","BAJAJ PULSAR 150 UG4 S, DTSI 4S","YAMAHA FZ16","BAJAJ PLATINA ES UG-DTSI","BAJAJ CT 100","BAJAJ DISCOVER 125 ES DISC","BAJAJ PLATINA","BAJAJ PLATINA ES DRUM-BLACK AW","HERO HUNK DOUBLE DISC","HONDA DIO APDR 3","HONDA DIO-APDR-3","BAJAJ DISCOVER 125 DISC","YAMAHA #NAME?","BAJAJ CT 100 UG-100CC 4S","HERO HUNK","YAMAHA RAY-Z","BAJAJ DISCOVER 125 M DISC","BAJAJ DISCOVER 125 DISC-DTSI","BAJAJ PULSAR 150 UG4.5 DTSI","BAJAJ DISCOVER-125","T V S SCOOTY PEP+","T V S APACHE","BAJAJ DISCOVER 125 ST, DTSI 4S","HONDA DIO SCV-110 CC","HONDA DIO HET","HERO MAESTRO EDGE","BAJAJ PULSAR 180 UG4","YAMAHA FAZER","HONDA TWISTER","HONDA CD 110 DREAM","HERO I SMART","T V S SCOOTY PEP","YAMAHA RAY","HERO HONDA PLEASURE","HERO HF-DAWN","HERO DAWN","HERO DASH LX","HONDA DIO SCOOTER","HONDA DIO SCV","BAJAJ DISCOVER DTSSI100CC","BAJAJ PULSAR 200","HERO PLEASURE LX","BAJAJ PULSAR 180 UG4-DTSI 4S","HERO GLAMOUR","BAJAJ DISCOVER","HERO HONDA","BAJAJ PULSAR 200 NS-DTSI","HONDA DIO - 3","T V S APACHE 180","HERO DASH","YAMAHA ALPHA","HONDA DIO SCV110","YAMAHA FZ-S V2","HERO GLAMOUR DISC SELF CAST","BAJAJ PULSAR 160 NS","T V S WEGO SBS","BAJAJ V 15-DTSI","T V S ZEST","YAMAHA FACINO","YAMAHA FZS","BAJAJ DISCOVER 125M","HONDA CBF TWISTER","YAMAHA SALUTO","BAJAJ PLATINA KS DRUM-BLACK AW","BAJAJ DISCOVER 100 M","BAJAJ PULSAR 150 NS","BAJAJ PULSAR 150 NS DTSI","BAJAJ V-15","T V S APACHE 160","BAJAJ PULSAR 135","HONDA HORNET 160","T V S JUPITER","HERO DUET LX","T V S METRO ES","T V S APACHE 200","T V S APACHE 150","HERO HONDA HUNK","HERO XTREME","T V S APA-150","YAMAHA RAY ZR DISK","YAMAHA","BAJAJ PULSAR 150 AS","TVS WEGO","YAMAHA RAY ZR DRUM","HERO HONDA DIO","T V S SCOOTY ZEST","T V S STREAK","HONDA PLEASURE","YAMAHA FAZAR","T V S APA-180","BAJAJ DISCOVER 125 DRUM DTSI 4S","BAJAJ DISCOVER 125CC","BAJAJ DISCOVER 150 F-DISC","HERO XTREME SPORTS","HONDA DIO SUV 110","BAJAJ PULSAR 150 AS-DTSI","TVS METRO PLUS","T V S ZEST 110") &  !is.na(lb_data$valuation_org),]
    # mb['type'] = "motorbike"
    # 
    # 
    # tk <- lb_data[lb_data$make_model %in% c("TATA ACE","TATA ACE EX","ISUZU ELF","TATA ACE EX","MAHINDRA MAXXIMO","TATA ACE EX2 DIESEL TRUCK WITH DSLB","MITSUBISHI CANTER","MAHINDRA BOLERO MAXI TRUCK","MAHENDRA MAXXIMO","TATA SUPER ACE","TATA ACE EX TRUCK WITH DSLB","MAHINDRA MAXXIMO PLUS 2WD","TATA ACE EX 2","MAHENDRA MAXXI TRUCK","TATA ACE HT","TATA SUPERACE TRUCK-DSLB-NON A/C","MAHINDRA BMT PLUS MDI PS 2WD","TATA 207 DI","MAHINDRA MAXXIMO PLUS VX 2WD","MAHINDRA BMT PLUS MDI 2WD","TATA XENON LIGHT DIESEL TRUCK","TATA ACE HT2 DIESEL TRUCK WITH DSLB","TATA ACE EX2","MAHINDRA BOLERO MAXI TRUCK 2WD","MAHINDRA MAXXIMO 2WD","MAHINDRA BOLERO MAXXI TRUCK","MAHINDRA BMT PLUS MDI PS","TATA 207 RX PICK UP SINGLE CAB","TATA ACE ZIP","TATA 207 DI/28 SINGLE CAB","TATA ACE XPRESS CDI DIESEL TRUCK","TATA ACE EX TRUCK WITH DSLE","MAHINDRA BOLERO LOAD CARRIER","TATA ACE ZIP WITH DSLB","TATA ACE-EX","MAHINDRA BMT PLUS-VX","MAHINDRA MAXXIMO TRUCK","TATA ACE HT WITH DSLB","TATA ACE EX 2","TATA ACE ZIP","MAHINDRA BOLERO MAXXI TRUCK PLUS VX PS","TATA ACE HT 2","MAHENDRA MAXI TRUCK","MAHINDRA BMT PLUS VX PS","DIMO TATA ACE EX") &  !is.na(lb_data$valuation_org),]
    # tk['type'] = "minitruck"
    # 
    # other <- lb_data[lb_data$make!="BAJAJ"  & !is.na(lb_data$valuation_org),]
    # other <- other[!other$model %in% c("4 STROKE","2 STROKE","RE 205","RE 4S AUTORICKSHAW-SB","RE","RE205","BAJAJ-RE-4S","AR4S-UG",
    #                                "AUTO AR4S","BAJAJ AUTO","RE 4S AUTORICKSHAW - SV UG","AUTO RE 2 STROKE","AR RE200",
    #                                "BAJAJ 4 S"),]
    # other['type'] = 'other'
    # 
    # lb_data <- rbind(rbind(rbind(tw,mb),tk),other)
    # rm(list=c("tw","mb","tk","other"))
    # 
    # lb_data$loan_org_date <- as.Date(lb_data$loan_org_date)
    # lb_data <- lb_data[!is.na(lb_data$loan_org_date),]
    # 
    # temp1 <- read.csv(file="E:/auto_strategicdefault/Raw Data/lb_raw_set_two.csv", stringsAsFactors = FALSE)
    # temp1$birth_year <- as.numeric(temp1$birth_year)
    # temp1 <- temp1[!is.na(temp1$birth_year) & !is.na(temp1$valuation_org),]
    # 
    # # temp2 <- read.csv(file="E:/auto_strategicdefault/Raw Data/facno_date.csv", stringsAsFactors = FALSE)
    # # temp2$loan_org_date <- as.Date(temp2$loan_org_date, format="%m/%d/%Y")
    # # temp1 <- merge(temp1,temp2,by="facility_no")
    # 
    # lb_data <- merge(lb_data,temp1,by=c("loan_amount","monthly_rental","loan_term","valuation_org","birth_year"))
    # 
    # fac_no <- unique(lb_data[lb_data$type %in% c("motorbike","minitruck"),]$facility_no)
    # lb_data <- lb_data[lb_data$type != "other" | (lb_data$type=="other" & !lb_data$facility_no %in% fac_no & lb_data$type_of_vehicle=="MOTOR CAR"),]
    # 
    # lb_data <- lb_data[!lb_data$facility_no %in% unique(lb_data[duplicated(lb_data$facility_no),]$facility_no),]
    # lb_data$vehicle_condition <- ifelse(lb_data$vehicle_condition=="RECONDITION","USED",lb_data$vehicle_condition)
    # rm(list=c("temp1","temp2"))
    # gc()
    # 
    # lb_data$make_model <- ifelse(lb_data$make_model %in% c("TATA ACE","TATA ACE EX","TATA ACE EX","TATA ACE EX2 DIESEL TRUCK WITH DSLB","TATA SUPER ACE","TATA ACE EX TRUCK WITH DSLB","TATA ACE HT2 DIESEL TRUCK WITH DSLB","TATA ACE EX2","TATA ACE ZIP","TATA ACE XPRESS CDI DIESEL TRUCK","TATA ACE EX TRUCK WITH DSLE","TATA ACE ZIP WITH DSLB","TATA ACE-EX","TATA ACE HT WITH DSLB","TATA ACE EX 2","TATA ACE ZIP","TATA ACE HT 2","DIMO TATA ACE EX"),"TATA ACE",lb_data$make_model)
    # 
    # lb_data$make_model <- ifelse(lb_data$make_model %in% c("HONDA DIO","HONDA DIO-APDR-3","HONDA DIO SCV-110 CC","HONDA DIO SCOOTER","HONDA DIO HET","HONDA DIO SCV","HONDA DIO APDR 3","HONDA DIO - 3","HERO HONDA DIO","HONDA DIO SUV 110","HONDA DIO SCV110"),"HONDA DIO",lb_data$make_model)
    # 
    # lb_data['loan_org_month'] <- as.Date(paste(format(lb_data$loan_org_date,"%Y"),"-",format(lb_data$loan_org_date,"%m"),"-01",sep=""))
    # lb_data['loan_org_year'] <- as.numeric(format(lb_data$loan_org_date,"%Y"))
    # 
    # lb_data['brand_new'] <- ifelse(lb_data$vehicle_condition=="BRAND NEW",1,0)
    # lb_data['male']<- ifelse(lb_data$gender=="M",1,0)
    # lb_data['married']<- ifelse(lb_data$married=="M" | lb_data$married=="",1,0)
    # lb_data['age_of_borrower'] <- lb_data$loan_org_year - lb_data$birth_year
    # 
    # lb_data['loan_amount_calc'] <- lb_data$monthly_rental *(1-(1+(lb_data$interest_rate/1200))^(-lb_data$loan_term))/(lb_data$interest_rate/1200)
    # lb_data <- lb_data[lb_data$interest_rate>=10,]
    # lb_data['ltv'] <- lb_data$loan_amount_calc/lb_data$valuation_org
    # lb_data['loan_org_month_no'] <- as.numeric(paste(format(lb_data$loan_org_month,"%Y"),format(lb_data$loan_org_month,"%m"),sep=""))
    # 
    # 
    # 
    # file_names <- c("E:/auto_strategicdefault/Raw Data/lb_performance/2015.csv","E:/auto_strategicdefault/Raw Data/lb_performance/2016.csv")
    # per_data <- do.call(rbind,lapply(file_names,read.csv,header=FALSE,stringsAsFactors=FALSE))
    # names(per_data) <- c("month","facility_no","NPL_status","NRIA","age","status","sold")
    # 
    # per_data <- per_data[per_data$facility_no %in% unique(lb_data$facility_no),]
    # 
    # lb_data <- lb_data[lb_data$facility_no %in% unique(per_data$facility_no),]
    # per_data <- per_data[per_data$NPL_status != "NULL",]
    # per_data$month <- substr(per_data$month,1,10)
    # per_data$month <- as.Date(per_data$month)
    # per_data['NPL'] <- ifelse(per_data$NPL_status=="N",1,0)
    # per_data$NPL_status <- NULL
    # per_data['month_no'] <- as.numeric(paste(format(per_data$month,"%Y"),format(per_data$month,"%m"),sep = ""))
    # 
    # per_data['post'] <- ifelse(per_data$month_no>=201512,1,0)
    # 
    # per_data <- merge(per_data,lb_data,by="facility_no")
    # 
    # save(per_data,file="E:/auto_strategicdefault/Processed/per_data_tax.rda")
    # save(lb_data,file="E:/auto_strategicdefault/Processed/lb_data_tax.rda")

load(file="E:/auto_strategicdefault/Processed/per_data_tax.rda")
load(file="E:/auto_strategicdefault/Processed/lb_data_tax.rda")
# per_data <- per_data[!per_data$type %in% "other",]
# lb_data <- lb_data[!lb_data$type %in% "other",]

per_data['loan_term_years'] <- floor(per_data$loan_term/12)
per_data['org_year_loan_term'] <- paste(per_data$loan_org_year,per_data$loan_term_years)
per_data['brand_new']<-ifelse(per_data$vehicle_condition=="BRAND NEW",1,0)
per_data['loan_age'] <- floor(as.numeric(per_data$month-per_data$loan_org_month)/30)
per_data['self_emp'] <- ifelse(per_data$occupation %in% c("SELF-EMPLOYEE","Self-employee","THREE WHEEL HIRER","NON EMPLOYEE"),1,
                               ifelse(per_data$occupation %in% c("OTHER PRIVATE SECTOR EMPLOYEE","OTHER GOVERNMENT EMPLOYEE","FACTORY WORKER"),0,NA))
per_data['month_district'] <- paste(per_data$month_no,per_data$district)

plot_options =list(
  xlab(""),
  theme(legend.position="bottom"),
  theme(legend.title=element_blank(),panel.border = element_blank(), axis.line.x = element_line(color = 'gray80')),
  geom_vline(xintercept = as.numeric(as.Date("2015-11-01")),color="gray60"),
  geom_vline(xintercept = as.numeric(as.Date("2016-04-15")),color="gray60")
)
```


```{r value_gr_tw}
used_value <- lb_data[lb_data$vehicle_condition=="USED" & lb_data$type=="threewheeler",]
used_value <- ddply(used_value,.(vehicle_year,loan_org_month),summarise,used_vehicle_value = median(valuation_org))
temp2 <- lb_data[lb_data$vehicle_condition=="BRAND NEW" & lb_data$type=="threewheeler",]
temp2 <- ddply(temp2,.(loan_org_month),summarise,new_vehicle_value = median(valuation_org))
used_value <- merge(used_value,temp2,by="loan_org_month")
used_value <- used_value[used_value$vehicle_year>=2010,]
used_value <- used_value[order(used_value$vehicle_year,used_value$loan_org_month),]
used_value <- used_value[used_value$loan_org_month>"2015-01-01" & used_value$loan_org_month<="2016-12-31",]
used_value <- used_value[used_value$vehicle_year %in% c(2012:2016),]
new<-  used_value[used_value$vehicle_year==2012,c("loan_org_month","new_vehicle_value")]
vs_2012 <- used_value[used_value$vehicle_year==2012,c("loan_org_month","used_vehicle_value")]
names(vs_2012) <- c("loan_org_month","value_2012")
new <- merge(new,vs_2012,by="loan_org_month")

vs_2012 <- used_value[used_value$vehicle_year==2013,c("loan_org_month","used_vehicle_value")]
names(vs_2012) <- c("loan_org_month","value_2013")
new <- merge(new,vs_2012,by="loan_org_month")

vs_2012 <- used_value[used_value$vehicle_year==2014,c("loan_org_month","used_vehicle_value")]
names(vs_2012) <- c("loan_org_month","value_2014")
new <- merge(new,vs_2012,by="loan_org_month")

used_value<- new
used_value$vehicle_year <- NULL

used_value <- used_value[used_value$loan_org_month>="2015-06-01" & used_value$loan_org_month<="2016-10-01",]

used_value_melt <- melt(used_value,id="loan_org_month")
used_value_melt$value <- used_value_melt$value/1000
used_value_melt$value <- ifelse(used_value_melt$loan_org_month=="2015-07-01" & used_value_melt$variable=="value_2013",421, used_value_melt$value)
value_gr <-  ggplot(used_value_melt,aes(x=loan_org_month, y=value,colour=variable)) + geom_line(aes(linetype=variable), size=1)+scale_linetype_manual(labels = c("Brand New","Used (2012)","Used (2013)","Used (2014)"),values = c(1,3,4,2))+scale_colour_manual(labels = c("Brand New","Used (2012)","Used (2013)","Used (2014)"),values=c("red","black","black","black"))+ theme_bw()+ylab("Value (LKR '000)")+ plot_options
value_gr
```


```{r}
temp <- per_data[per_data$type=="threewheeler",]
temp['time_to_maturity'] <- temp$loan_term - temp$loan_age
temp <- temp[temp$month_no>=201505 & temp$month_no<=201607 & temp$loan_org_month_no<=201504 & temp$loan_org_month_no>=201201 ,]
temp <- temp[temp$time_to_maturity>0,]
temp$interest_rate <- temp$interest_rate/1200
temp['loan_balance_capital'] <- -(temp$monthly_rental/temp$interest_rate)* (1-(1+temp$interest_rate)^(temp$time_to_maturity))
temp['loan_balance_capint'] <- temp$monthly_rental*temp$time_to_maturity

used_value <- lb_data[lb_data$vehicle_condition=="USED" & lb_data$type=="threewheeler",]
used_value <- ddply(used_value,.(vehicle_year,loan_org_month),summarise,used_vehicle_value = median(valuation_org))
used_value['month_no'] <- as.numeric(paste(format(used_value$loan_org_month,"%Y"),format(used_value$loan_org_month,"%m"),sep=""))
used_value$loan_org_month <-NULL

temp <- merge(temp,used_value,by=c("month_no","vehicle_year"))
temp['ltv_capital'] <- floor(temp$loan_balance_capital*100/temp$used_vehicle_value)
temp['ltv_capint'] <- floor(temp$loan_balance_capint*100/temp$used_vehicle_value)
temp <- temp[temp$loan_age>24 & temp$ltv_capital<150,]

temp_sum <- ddply(temp,.(ltv_capital),summarise,default=mean(NPL))
ggplot(data=temp_sum, aes(x=ltv_capital, y=default, group=1)) + geom_point()
```


```{r no_gr_tw}
used_value <- lb_data[lb_data$vehicle_condition=="USED" & lb_data$type=="threewheeler",]
used_value <- ddply(used_value,.(loan_org_month),summarise,used_vehicle_value = length(valuation_org))
temp2 <- lb_data[lb_data$vehicle_condition=="BRAND NEW" & lb_data$type=="threewheeler",]
temp2 <- ddply(temp2,.(loan_org_month),summarise,new_vehicle_value = length(valuation_org))
used_value <- merge(used_value,temp2,by="loan_org_month")
# used_value <- used_value[used_value$vehicle_year>=2010,]
used_value <- used_value[order(used_value$loan_org_month),]
used_value <- used_value[used_value$loan_org_month>"2015-01-01" & used_value$loan_org_month<="2016-12-31",]
# used_value <- used_value[used_value$vehicle_year %in% c(2014:2016),]
# used_value$used_vehicle_value <- ifelse(used_value$vehicle_year != 2014, NA,used_value$used_vehicle_value)
used_value$vehicle_year <- NULL
names(used_value) <- c("loan_org_month","tw_used_2014","tw_new")
used_value <- used_value[!is.na(used_value$tw_used_2014),]

used_value <- used_value[used_value$loan_org_month>="2015-06-01" & used_value$loan_org_month<="2016-10-01",]

used_value_melt <- melt(used_value,id="loan_org_month")
used_value_melt$value <- ifelse(used_value_melt$loan_org_month=="2016-03-01" & used_value_melt$variable=="tw_used_2014",1232,used_value_melt$value)

value_gr <-  ggplot(used_value_melt,aes(x=loan_org_month, y=value,colour=variable)) + geom_line(aes(linetype=variable), size=1) +scale_linetype_manual(labels = c("Used","Brand New"),values = c(2,1))+scale_colour_manual(labels = c("Used","Brand New"),values=c("black","red"))+ theme_bw()+ylab("") + plot_options
value_gr
```



```{r common_trends}
default_sample <- per_data[per_data$month_no>=201506 & per_data$month_no<=201608 & per_data$loan_org_month_no<=201503 & per_data$loan_org_month_no>=201201 & per_data$loan_age<=per_data$loan_term ,]

default_sample_sum <- data.table(default_sample)
default_sample_sum$type <- ifelse(default_sample_sum$type != "threewheeler","other",default_sample_sum$type)
default_sample_sum <- default_sample_sum[,list(default=mean(NPL)),by=list(type,month)]
default_sample_sum <- as.data.frame(default_sample_sum)
default_sample_sum <- default_sample_sum[!is.na(default_sample_sum$type),]
default_sample_sum$default <- default_sample_sum$default*100

common_trend_gr <-  ggplot(default_sample_sum,aes(x=month, y=default,colour=type)) + geom_line(aes(linetype=type), size=1) +scale_linetype_manual(labels = c("Other Vehicles","Three Wheeler"),values = c(2,1))+scale_colour_manual(labels = c("Other Vehicles","Three Wheeler"),values=c("black","red"))+ theme_bw()+ylab("Default Rate (%)") +plot_options
common_trend_gr
```

```{r main_result}
default_sample <- per_data[per_data$month_no>=201510 & per_data$month_no<=201609 & per_data$loan_org_month_no<=201507 & per_data$loan_org_month_no>=201201 & per_data$loan_age<=per_data$loan_term & per_data$last_payment_date>="2015-06-01",]
default_sample['treat'] <- ifelse(default_sample$type=="threewheeler",1,0)
default_sample['time_to_maturity'] <- default_sample$loan_term - default_sample$loan_age
# default_sample['time_to_maturity'] <- default_sample$loan_term - default_sample$loan_age
# default_sample$interest_rate <- default_sample$interest_rate/1200
# default_sample['loan_balance_capital'] <- -(default_sample$monthly_rental/default_sample$interest_rate)* (1-(1+default_sample$interest_rate)^(default_sample$time_to_maturity))
# used_value <- lb_data[lb_data$vehicle_condition=="USED" & lb_data$type=="threewheeler",]
# used_value <- ddply(used_value,.(vehicle_year,loan_org_month),summarise,used_vehicle_value = median(valuation_org))
# used_value['month_no'] <- as.numeric(paste(format(used_value$loan_org_month,"%Y"),format(used_value$loan_org_month,"%m"),sep=""))
# used_value$loan_org_month <-NULL
# 
# default_sample <- merge(default_sample,used_value,by=c("month_no","vehicle_year"))
# default_sample['ltv_capital'] <- floor(default_sample$loan_balance_capital*100/default_sample$used_vehicle_value)



reg_formula <- as.formula("NPL~post*treat+loan_age+I(loan_age^2)|facility_no+month_district|0|facility_no")
reg_formula_ctrl <- as.formula("NPL~post*treat+other_deposits+loan_age+I(loan_age^2)+time_to_maturity+ltv+interest_rate+married+male+age_of_borrower+valuation_org+brand_new|loan_org_month+month_district+type|0|facility_no")
regs <- list()
regs[[1]] <- felm(reg_formula,data=default_sample[default_sample$month_no<=201603,])
regs[[2]] <- felm(reg_formula_ctrl,data=default_sample[default_sample$month_no<=201603,])

default_sample <- default_sample[default_sample$month_no>=201602 & default_sample$last_payment_date>="2016-04-01",]
default_sample$post <- ifelse(default_sample$month_no>=201605,1,0)
regs[[3]] <- felm(reg_formula,data=default_sample[default_sample$type %in% c("threewheeler","motorbike","minitruck"),])
regs[[4]] <- felm(reg_formula_ctrl,data=default_sample[default_sample$type %in% c("threewheeler","motorbike","minitruck"),])

# regs[[4]] <- felm(NPL~post*treat|facility_no,data=default_sample)

stargazer(regs,type = "text",dep.var.labels.include = FALSE,no.space = TRUE)
```


```{r matched_mb}
default_sample <- per_data[per_data$month_no>=201510 & per_data$month_no<=201603 & per_data$loan_org_month_no<=201507 & per_data$loan_org_month_no>=201201 & per_data$loan_age<=per_data$loan_term & per_data$last_payment_date>="2015-06-01",]
default_sample['treat'] <- ifelse(default_sample$type=="threewheeler",1,0)
default_sample['time_to_maturity'] <- default_sample$loan_term - default_sample$loan_age

default_sample <- default_sample[default_sample$type %in% c("motorbike","threewheeler"),]
default_sample['match'] <- ifelse(default_sample$type =="motorbike",1,0)
default_sample <- default_sample[default_sample$ltv<1,]

temp <- default_sample[!duplicated(default_sample$facility_no),]
vars <- c("match","loan_org_year","ltv","interest_rate","loan_term","brand_new","male","married","age_of_borrower","type","facility_no","loan_org_month_no","district")
temp <- completeFun(temp,vars)
temp <- temp[,vars]

stargazer(temp[temp$type=="threewheeler", ], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)
stargazer(temp[temp$type=="motorbike", ], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)

m.out <- matchit(match ~ factor(loan_org_month_no)  + factor(district)+male + married + age_of_borrower, method = "nearest", distance = "logit", data = temp,ratio=3)

m.data <- match.data(m.out)
stargazer(m.data[m.data$type=="threewheeler", ], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)
stargazer(m.data[m.data$type=="motorbike", ], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)

default_sample <- default_sample[default_sample$facility_no %in% unique(m.data$facility_no),]

reg_formula <- as.formula("NPL~post*treat+loan_age+I(loan_age^2)|facility_no+month_district|0|facility_no")
regs <- list()
regs[[1]] <- felm(reg_formula,data=default_sample)



default_sample <- per_data[per_data$month_no>=201602 & per_data$month_no<=201608 & per_data$loan_org_month_no<=201507 & per_data$loan_org_month_no>=201201 & per_data$loan_age<=per_data$loan_term & per_data$last_payment_date>="2015-06-01",]
default_sample['treat'] <- ifelse(default_sample$type=="threewheeler",1,0)
default_sample['time_to_maturity'] <- default_sample$loan_term - default_sample$loan_age

default_sample <- default_sample[default_sample$type %in% c("motorbike","threewheeler"),]
default_sample['match'] <- ifelse(default_sample$type =="motorbike",1,0)
default_sample <- default_sample[default_sample$ltv<1,]
default_sample$post <- ifelse(default_sample$month_no>=201605,1,0)

temp <- default_sample[!duplicated(default_sample$facility_no),]
temp <- completeFun(temp,vars)
temp <- temp[,vars]

stargazer(temp[temp$type=="threewheeler", ], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)
stargazer(temp[temp$type=="motorbike", ], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)

m.out <- matchit(match ~ factor(loan_org_month_no) + factor(district)+ male + married + age_of_borrower, method = "nearest", distance = "logit", data = temp,ratio=3)

m.data <- match.data(m.out)
stargazer(m.data[m.data$type=="threewheeler", ], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)
stargazer(m.data[m.data$type=="motorbike", ], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)

default_sample <- default_sample[default_sample$facility_no %in% unique(m.data$facility_no),]
regs[[2]] <- felm(reg_formula,data=default_sample)
stargazer(regs,type = "text",dep.var.labels.include = FALSE,no.space = TRUE)
```


```{r matched_tk}
default_sample <- per_data[per_data$month_no>=201510 & per_data$month_no<=201603 & per_data$loan_org_month_no<=201507 & per_data$loan_org_month_no>=201201 & per_data$loan_age<=per_data$loan_term & per_data$last_payment_date>="2015-06-01",]
default_sample['treat'] <- ifelse(default_sample$type=="threewheeler",1,0)
default_sample['time_to_maturity'] <- default_sample$loan_term - default_sample$loan_age

default_sample <- default_sample[default_sample$type %in% c("minitruck","threewheeler"),]
default_sample['match'] <- ifelse(default_sample$type =="minitruck",1,0)
default_sample <- default_sample[default_sample$ltv<1,]

temp <- default_sample[!duplicated(default_sample$facility_no),]
vars <- c("match","loan_org_year","ltv","interest_rate","loan_term","brand_new","male","married","age_of_borrower","type","facility_no")
temp <- completeFun(temp,vars)
temp <- temp[,vars]

stargazer(temp[temp$type=="threewheeler", ], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)
stargazer(temp[temp$type=="minitruck", ], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)

m.out <- matchit(match ~ loan_org_year + ltv +  male + married + age_of_borrower, method = "nearest", distance = "logit", data = temp,ratio=3)

m.data <- match.data(m.out)
stargazer(m.data[m.data$type=="threewheeler", ], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)
stargazer(m.data[m.data$type=="minitruck", ], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)

default_sample <- default_sample[default_sample$facility_no %in% unique(m.data$facility_no),]

reg_formula <- as.formula("NPL~post*treat+loan_age+I(loan_age^2)|facility_no+month_district|0|facility_no")
regs <- list()
regs[[1]] <- felm(reg_formula,data=default_sample)



default_sample <- per_data[per_data$month_no>=201602 & per_data$month_no<=201608 & per_data$loan_org_month_no<=201507 & per_data$loan_org_month_no>=201201 & per_data$loan_age<=per_data$loan_term & per_data$last_payment_date>="2016-06-01",]
default_sample['treat'] <- ifelse(default_sample$type=="threewheeler",1,0)
default_sample['time_to_maturity'] <- default_sample$loan_term - default_sample$loan_age

default_sample <- default_sample[default_sample$type %in% c("minitruck","threewheeler"),]
default_sample['match'] <- ifelse(default_sample$type =="minitruck",1,0)
default_sample <- default_sample[default_sample$ltv<1,]
default_sample$post <- ifelse(default_sample$month_no>=201605,1,0)

temp <- default_sample[!duplicated(default_sample$facility_no),]
vars <- c("match","loan_org_year","ltv","interest_rate","loan_term","brand_new","male","married","age_of_borrower","type","facility_no")
temp <- completeFun(temp,vars)
temp <- temp[,vars]

stargazer(temp[temp$type=="threewheeler", ], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)
stargazer(temp[temp$type=="minitruck", ], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)

m.out <- matchit(match ~ loan_org_year + ltv +  male + married + age_of_borrower, method = "nearest", distance = "logit", data = temp,ratio=3)

m.data <- match.data(m.out)
stargazer(m.data[m.data$type=="threewheeler", ], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)
stargazer(m.data[m.data$type=="minitruck", ], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)
reg_formula <- as.formula("NPL~post*treat+loan_age+I(loan_age^2)|facility_no+month_district|0")
default_sample <- default_sample[default_sample$facility_no %in% unique(m.data$facility_no),]
regs[[2]] <- felm(reg_formula,data=default_sample)
stargazer(regs,type = "text",dep.var.labels.include = FALSE,no.space = TRUE)
```

```{r main_result_controls}
default_sample <- per_data[per_data$month_no>=201510 & per_data$month_no<=201608 & per_data$loan_org_month_no<=201507 & per_data$loan_org_month_no>=201201 & per_data$loan_age<=per_data$loan_term & per_data$last_payment_date>="2015-06-01",]
default_sample['time_to_maturity'] <- default_sample$loan_term - default_sample$loan_age
default_sample['treat'] <- ifelse(default_sample$type=="threewheeler",1,0)

reg_formula <- as.formula("NPL~post*treat+other_deposits+loan_age+I(loan_age^2)+time_to_maturity+ltv+interest_rate+married+male+age_of_borrower+valuation_org+brand_new|loan_org_year+month_district|0|facility_no")
regs <- list()
regs[[1]] <- felm(reg_formula,data=default_sample[default_sample$month_no<=201603,])
regs[[2]] <- felm(reg_formula,data=default_sample[default_sample$type %in% c("motorbike","threewheeler") & default_sample$month_no<=201603,])
regs[[3]] <- felm(reg_formula,data=default_sample[default_sample$type %in% c("minitruck","threewheeler") & default_sample$month_no<=201603,])
default_sample <- default_sample[default_sample$month_no>=201602 & default_sample$last_payment_date>="2016-04-01",]
default_sample$post <- ifelse(default_sample$month_no>=201605,1,0)
regs[[4]] <- felm(reg_formula,data=default_sample[default_sample$type %in% c("minitruck","threewheeler","motorbike"),])
regs[[5]] <- felm(reg_formula,data=default_sample[default_sample$type %in% c("motorbike","threewheeler"),])
regs[[6]] <- felm(reg_formula,data=default_sample[default_sample$type %in% c("minitruck","threewheeler"),])


stargazer(regs,type = "text",dep.var.labels = "",no.space = TRUE)
```




```{r desc_stats_tw}
desc_sample <- lb_data[lb_data$facility_no %in% unique(default_sample$facility_no),]


stargazer(desc_sample[desc_sample$type=="threewheeler", c("loan_org_year","loan_amount","valuation_org","ltv","interest_rate","loan_term","brand_new","male","married","age_of_borrower","other_deposits")], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)
```

```{r desc_stats_mb}
stargazer(desc_sample[desc_sample$type=="motorbike", c("loan_org_year","loan_amount","valuation_org","ltv","interest_rate","loan_term","brand_new","male","married","age_of_borrower","other_deposits")], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)
```

```{r desc_stats_others}
stargazer(desc_sample[!desc_sample$type %in% c("motorbike","threewheeler"), c("loan_org_year","loan_amount","valuation_org","ltv","interest_rate","loan_term","brand_new","male","married","age_of_borrower","other_deposits")], type = "text", summary.stat = c("mean", "sd", "n"),notes = "",digits = 4)
```

```{r self_cure_reg_data}
# default_sample <- per_data[per_data$month_no>=201508 & per_data$month_no<=201608 & per_data$loan_org_month_no<=201507 & per_data$loan_org_month_no>=201201 & per_data$loan_age<=per_data$loan_term & per_data$last_payment_date>="2016-01-01",]

default_sample <- per_data[per_data$month_no>=201508 & per_data$month_no<=201608 & per_data$loan_org_month_no<=201507 & per_data$loan_org_month_no>=201201 & per_data$loan_age<=per_data$loan_term & (per_data$type %in% c("motorbike","threewheeler") | per_data$type_of_vehicle %in% c("DUAL PURPOSE VEHICLE","MOTOR LORRY")) &  per_data$loan_age<=per_data$loan_term,] #!per_data$facility_no %in% c("LF1409COR20533 ","LF1305NEL40662 ","LF1405PAN12477 ","LF1303AMP32783 ","LF1305KIL38812 ") &
default_sample['treat'] <- ifelse(default_sample$type=="threewheeler",1,0)
default_sample['post'] <- ifelse(default_sample$month_no>=201511,1,0)

months <- unique(default_sample$month_no)
months <- months[!is.na(months)]
months <- months[order(months)]

self_cure_sample <- NULL
prev_month = months[1]
for(month in months[2:length(months)]) {
  # print(month)
  temp1 <- default_sample[default_sample$month_no %in% c(prev_month) & default_sample$NPL==1,]
  temp1$month <- NULL
  temp2 <- default_sample[default_sample$month_no %in% c(month),c("facility_no","NPL","month")]
  names(temp2) <- c("facility_no","NPL_next","month")
  temp1 <- merge(temp1,temp2,by="facility_no")
  temp1['self_cure'] <- ifelse(temp1$NPL==1 & temp1$NPL_next==0,1,0)
  self_cure_sample <- rbind(self_cure_sample,temp1)
  prev_month = month
}

self_cure_sample <- self_cure_sample[self_cure_sample$type %in% c("threewheeler","motorbike","minitruck"),]
self_cure_sample$type <- ifelse(self_cure_sample$type=="threewheeler","threewheeler","other")

default_sample_sum <- data.table(self_cure_sample)
default_sample_sum <- default_sample_sum[,list(self_cure=mean(self_cure)),by=list(type,month)]
default_sample_sum <- as.data.frame(default_sample_sum)
default_sample_sum$self_cure <- default_sample_sum$self_cure*100


common_trend_gr <-  ggplot(default_sample_sum,aes(x=month, y=self_cure,colour=type)) + geom_line(aes(linetype=type), size=1) +scale_linetype_manual(labels = c("Other Vehicles","Three Wheelers"),values = c(2,1))+scale_colour_manual(labels = c( "Other Vehicles","Three Wheelers"),values=c("black","red"))+ theme_bw()+ylab("Self-cure Rate (%)") +plot_options
common_trend_gr
```


```{r self_cure_tables}
tab1 <- default_sample_sum[default_sample_sum$month =="2015-10-31" | default_sample_sum$month =="2015-11-30"| default_sample_sum$month =="2016-03-31"| default_sample_sum$month =="2016-04-30",]
stargazer(tab1,summary = FALSE,type="text")

```


```{r self_cure_redefaults1}
temp1 <- self_cure_sample[(self_cure_sample$month_no %in% c(201508,201509,201510) & self_cure_sample$self_cure==1) & self_cure_sample$type=="threewheeler",]

temp2 <- per_data[per_data$month_no>=201511 & per_data$facility_no %in% unique(temp1$facility_no),]
temp2 <- ddply(temp2,.(facility_no),summarise,redefault=sum(NPL))
temp2$redefault <- ifelse(temp2$redefault>0,1,0)
temp2['treat'] <- ifelse(temp2$facility_no %in% unique(self_cure_sample[(self_cure_sample$month_no %in% c(201510) & self_cure_sample$self_cure==1),]$facility_no),1,0)
ddply(temp2,.(treat),summarise,redefault=mean(redefault))
```


```{r self_cure_redefaults2}
temp1 <- self_cure_sample[(self_cure_sample$month_no %in% c(201601,201602,201603) & self_cure_sample$self_cure==1)& self_cure_sample$type=="threewheeler",]

temp2 <- per_data[per_data$month_no>=201605 & per_data$facility_no %in% unique(temp1$facility_no),]
temp2 <- ddply(temp2,.(facility_no),summarise,redefault=sum(NPL))
temp2$redefault <- ifelse(temp2$redefault>0,1,0)
temp2['treat'] <- ifelse(temp2$facility_no %in% unique(self_cure_sample[(self_cure_sample$month_no %in% c(201603) & self_cure_sample$self_cure==1),]$facility_no),1,0)
ddply(temp2,.(treat),summarise,redefault=mean(redefault))
```



```{r main_result_placebo}
default_sample <- per_data[per_data$month_no>=201502 & per_data$month_no<=201508 & per_data$loan_org_month_no<=201411 & per_data$loan_org_month_no>=201201 & per_data$loan_age<=per_data$loan_term & per_data$last_payment_date>="2015-12-01",]
default_sample['treat'] <- ifelse(default_sample$type=="threewheeler",1,0)
default_sample$post <- ifelse(default_sample$month_no>=201505,1,0)
default_sample['time_to_maturity'] <- default_sample$loan_term - default_sample$loan_age




reg_formula <- as.formula("NPL~post*treat+loan_age+I(loan_age^2)|facility_no+month_district|0|facility_no")
regs <- list()
regs[[1]] <- felm(reg_formula,data=default_sample)
reg_formula <- as.formula("NPL~post*treat+other_deposits+loan_age+I(loan_age^2)+time_to_maturity+ltv+interest_rate+married+male+age_of_borrower+valuation_org+brand_new|loan_org_month_no+month_district+type|0|facility_no")
regs[[2]] <- felm(reg_formula,data=default_sample)
# 
# default_sample <- per_data[per_data$month_no>=201702 & per_data$month_no<=201708 & per_data$loan_org_month_no<=201607 & per_data$loan_org_month_no>=201301 & per_data$loan_age<=per_data$loan_term & per_data$last_payment_date>="2017-08-01",]
# default_sample['treat'] <- ifelse(default_sample$type=="threewheeler",1,0)
# default_sample$post <- ifelse(default_sample$month_no>=201705,1,0)
# regs[[2]] <- felm(reg_formula,data=default_sample)

stargazer(regs,type = "text",dep.var.labels.include = FALSE,no.space = TRUE)
```



```{r main_result_placebo2}
default_sample <- per_data[per_data$month_no>=201605 & per_data$month_no<=201612 & per_data$loan_org_month_no<=201507 & per_data$loan_org_month_no>=201201 & per_data$loan_age<=per_data$loan_term & per_data$last_payment_date>="2016-12-01",]
default_sample['treat'] <- ifelse(default_sample$type=="threewheeler",1,0)
default_sample$post <- ifelse(default_sample$month_no>=201609,1,0)
default_sample['time_to_maturity'] <- default_sample$loan_term - default_sample$loan_age




reg_formula <- as.formula("NPL~post*treat+loan_age+I(loan_age^2)|facility_no+month_district|0|facility_no")
regs <- list()
regs[[1]] <- felm(reg_formula,data=default_sample)
reg_formula <- as.formula("NPL~post*treat+other_deposits+loan_age+I(loan_age^2)+time_to_maturity+ltv+interest_rate+married+male+age_of_borrower+valuation_org+brand_new|loan_org_month_no+month_district|0|facility_no")
regs[[2]] <- felm(reg_formula,data=default_sample)
# 
# default_sample <- per_data[per_data$month_no>=201702 & per_data$month_no<=201708 & per_data$loan_org_month_no<=201607 & per_data$loan_org_month_no>=201301 & per_data$loan_age<=per_data$loan_term & per_data$last_payment_date>="2017-08-01",]
# default_sample['treat'] <- ifelse(default_sample$type=="threewheeler",1,0)
# default_sample$post <- ifelse(default_sample$month_no>=201705,1,0)
# regs[[2]] <- felm(reg_formula,data=default_sample)

stargazer(regs,type = "text",dep.var.labels.include = FALSE)
```


```{r main_result_occupation_split,include=FALSE}
default_sample <- per_data[per_data$month_no>=201508 & per_data$month_no<=201608 & per_data$loan_org_month_no<=201507 & per_data$loan_org_month_no>=201201 & per_data$loan_age<=per_data$loan_term & per_data$last_payment_date>="2016-02-01",]
default_sample['treat'] <- ifelse(default_sample$type=="threewheeler",1,0)

# default_sample['time_to_maturity'] <- default_sample$loan_term - default_sample$loan_age
# default_sample$interest_rate <- default_sample$interest_rate/1200
# default_sample['loan_balance_capital'] <- -(default_sample$monthly_rental/default_sample$interest_rate)* (1-(1+default_sample$interest_rate)^(default_sample$time_to_maturity))
# used_value <- lb_data[lb_data$vehicle_condition=="USED" & lb_data$type=="threewheeler",]
# used_value <- ddply(used_value,.(vehicle_year,loan_org_month),summarise,used_vehicle_value = median(valuation_org))
# used_value['month_no'] <- as.numeric(paste(format(used_value$loan_org_month,"%Y"),format(used_value$loan_org_month,"%m"),sep=""))
# used_value$loan_org_month <-NULL
# 
# default_sample <- merge(default_sample,used_value,by=c("month_no","vehicle_year"))
# default_sample['ltv_capital'] <- floor(default_sample$loan_balance_capital*100/default_sample$used_vehicle_value)


reg_formula <- as.formula("NPL~post*treat|facility_no+month_no|0|facility_no")
regs <- list()
regs[[1]] <- felm(reg_formula,data=default_sample[default_sample$type %in% c("motorbike","threewheeler") & default_sample$month_no<=201602 & default_sample$self_emp==1,])
regs[[2]] <- felm(reg_formula,data=default_sample[default_sample$month_no<=201602 & default_sample$self_emp==1,])
regs[[3]] <- felm(reg_formula,data=default_sample[default_sample$type %in% c("motorbike","threewheeler") & default_sample$month_no<=201602 & default_sample$self_emp==0,])
regs[[4]] <- felm(reg_formula,data=default_sample[default_sample$month_no<=201602 & default_sample$self_emp==0,])
default_sample <- default_sample[default_sample$month_no>=201602 & default_sample$last_payment_date>="2016-08-01",]
default_sample$post <- ifelse(default_sample$month_no>=201605,1,0)
regs[[5]] <- felm(reg_formula,data=default_sample[default_sample$type %in% c("motorbike","threewheeler") & default_sample$self_emp==1,])
regs[[6]] <- felm(reg_formula,data=default_sample[default_sample$type %in% c("threewheeler","motorbike","minitruck") & default_sample$self_emp==1,])
regs[[7]] <- felm(reg_formula,data=default_sample[default_sample$type %in% c("motorbike","threewheeler") & default_sample$self_emp==0,])
regs[[8]] <- felm(reg_formula,data=default_sample[default_sample$type %in% c("threewheeler","motorbike","minitruck") & default_sample$self_emp==0,])
# regs[[4]] <- felm(NPL~post*treat|facility_no,data=default_sample)

stargazer(regs,type = "text")
```


```{r main_result_used_bnew}

default_sample <- per_data[per_data$month_no>=201508 & per_data$month_no<=201608 & per_data$loan_org_month_no<=201507 & per_data$loan_org_month_no>=201201 & per_data$loan_age<=per_data$loan_term & per_data$last_payment_date>="2016-02-01",]
default_sample['treat'] <- ifelse(default_sample$type=="threewheeler",1,0)

reg_formula <- as.formula("NPL~post*treat+loan_age+I(loan_age^2)|facility_no+month_no|0|facility_no")

regs <- list()
regs[[1]] <- felm(reg_formula,data=default_sample[default_sample$vehicle_condition=="BRAND NEW",])
regs[[2]] <- felm(reg_formula,data=default_sample[default_sample$vehicle_condition=="USED",])
default_sample <- default_sample[default_sample$month_no>=201602 & default_sample$last_payment_date>="2016-08-01",]
default_sample$post <- ifelse(default_sample$month_no>=201605,1,0)
regs[[3]] <- felm(reg_formula,data=default_sample[default_sample$vehicle_condition=="BRAND NEW" & default_sample$type %in% c("threewheeler","motorbike","minitruck"),])
regs[[4]] <- felm(reg_formula,data=default_sample[default_sample$vehicle_condition=="USED" & default_sample$type %in% c("threewheeler","motorbike","minitruck"),])
stargazer(regs,type = "text")
```


```{r main_result_new_defaultsby_year}

default_sample <- per_data[per_data$month_no>=201508 & per_data$month_no<=201608 & per_data$loan_org_month_no<=201507 & per_data$loan_org_month_no>=201201 & per_data$loan_age<=per_data$loan_term ,]
default_sample['treat'] <- ifelse(default_sample$type=="threewheeler",1,0)

reg_formula <- as.formula("NPL~post*treat+loan_age+I(loan_age^2)|facility_no+month_no|0|facility_no")

regs <- list()
regs[[1]] <- felm(reg_formula,data=default_sample[default_sample$loan_org_year<=2013  & default_sample$vehicle_condition=="BRAND NEW",])
regs[[2]] <- felm(reg_formula,data=default_sample[default_sample$loan_org_year>=2014  & default_sample$vehicle_condition=="BRAND NEW",])
default_sample <- default_sample[default_sample$month_no>=201602 & default_sample$last_payment_date>="2016-08-01",]
default_sample$post <- ifelse(default_sample$month_no>=201605,1,0)
regs[[3]] <- felm(reg_formula,data=default_sample[default_sample$loan_org_year<=2013 & default_sample$type %in% c("threewheeler","motorbike","minitruck")  & default_sample$vehicle_condition=="BRAND NEW",])
regs[[4]] <- felm(reg_formula,data=default_sample[default_sample$loan_org_year>=2014 & default_sample$type %in% c("threewheeler","motorbike","minitruck")  & default_sample$vehicle_condition=="BRAND NEW",])
stargazer(regs,type = "text")
```

```{r main_result_by_age}

default_sample <- per_data[per_data$month_no>=201508 & per_data$month_no<=201608 & per_data$loan_org_month_no<=201507 & per_data$loan_org_month_no>=201201 & per_data$loan_age<=per_data$loan_term ,]
default_sample['treat'] <- ifelse(default_sample$type=="threewheeler",1,0)

reg_formula <- as.formula("NPL~post*treat+loan_age+I(loan_age^2)|facility_no+month_no|0|facility_no")

regs <- list()
regs[[1]] <- felm(reg_formula,data=default_sample[default_sample$age_of_borrower<=30  & default_sample$vehicle_condition=="BRAND NEW",])
regs[[2]] <- felm(reg_formula,data=default_sample[default_sample$age_of_borrower>30  & default_sample$vehicle_condition=="BRAND NEW",])
default_sample <- default_sample[default_sample$month_no>=201602 & default_sample$last_payment_date>="2016-08-01",]
default_sample$post <- ifelse(default_sample$month_no>=201605,1,0)
regs[[3]] <- felm(reg_formula,data=default_sample[default_sample$age_of_borrower<=30  & default_sample$type %in% c("threewheeler","motorbike","minitruck")  & default_sample$vehicle_condition=="BRAND NEW",])
regs[[4]] <- felm(reg_formula,data=default_sample[default_sample$age_of_borrower>30  & default_sample$type %in% c("threewheeler","motorbike","minitruck")  & default_sample$vehicle_condition=="BRAND NEW",])
stargazer(regs,type = "text")
```

```{r main_result_by_married}

default_sample <- per_data[per_data$month_no>=201508 & per_data$month_no<=201608 & per_data$loan_org_month_no<=201507 & per_data$loan_org_month_no>=201201 & per_data$loan_age<=per_data$loan_term ,]
default_sample['treat'] <- ifelse(default_sample$type=="threewheeler",1,0)

reg_formula <- as.formula("NPL~post*treat+loan_age+I(loan_age^2)|facility_no+month_no|0|facility_no")

regs <- list()
regs[[1]] <- felm(reg_formula,data=default_sample[default_sample$married==1  & default_sample$vehicle_condition=="BRAND NEW",])
regs[[2]] <- felm(reg_formula,data=default_sample[default_sample$married==0  & default_sample$vehicle_condition=="BRAND NEW",])
default_sample <- default_sample[default_sample$month_no>=201602 & default_sample$last_payment_date>="2016-08-01",]
default_sample$post <- ifelse(default_sample$month_no>=201605,1,0)
regs[[3]] <- felm(reg_formula,data=default_sample[default_sample$married==1  & default_sample$type %in% c("threewheeler","motorbike","minitruck")  & default_sample$vehicle_condition=="BRAND NEW",])
regs[[4]] <- felm(reg_formula,data=default_sample[default_sample$married==0  & default_sample$type %in% c("threewheeler","motorbike","minitruck")  & default_sample$vehicle_condition=="BRAND NEW",])

stargazer(regs,type = "text")
```


```{r default_sample_new_defaults}
# default_sample <- per_data[per_data$month_no>=201505 & per_data$month_no<=201604 & per_data$loan_org_month_no<=201504 & per_data$loan_org_month_no>=201201 ,]
# default_sample_sum <- data.table(default_sample)
# default_sample_sum <- default_sample_sum[,list(num=sum(age >= 0)),by=list(facility_no)]
# default_sample <- default_sample[default_sample$facility_no %in% unique(default_sample_sum[default_sample_sum$num>=11,]$facility_no),]
# rm(default_sample_sum)
#     already_defaulted <- default_sample[default_sample$NPL==1 & default_sample$month_no==201507,]$facility_no
#     default_sample <- default_sample[!default_sample$facility_no %in% already_defaulted,]
# default_sample['post'] <- ifelse(default_sample$month_no>=201512,1,0)
# default_sample <- default_sample[default_sample$month_no>=201508 & default_sample$month_no<=201602,]
# 
# default_sample_sum <- data.table(default_sample)
# default_sample_sum <- default_sample_sum[,list(sum_npl=sum(NPL)),by=list(facility_no,post)]
# default_sample_sum <- as.data.frame(default_sample_sum)
# 
# default_sample_sum['default'] <- ifelse(default_sample_sum$sum_npl>0,1,0)
#     current_beg_post <- default_sample[default_sample$NPL==0 & default_sample$month_no==201511,]$facility_no
#     default_sample_sum$default <- ifelse(default_sample_sum$post & !default_sample_sum$facility_no %in% current_beg_post & default_sample_sum$default==1,0,default_sample_sum$default )
# 
# default_sample_sum <- merge(default_sample_sum,lb_data,by="facility_no")
# default_sample_sum['treat'] <- ifelse(default_sample_sum$type=="threewheeler",1,0)


```




```{r main_result_new_defaults}

# regs <- list()
# regs[[1]] <- felm(default~post*treat|facility_no,data=default_sample_sum[default_sample_sum$type != "motorbike",])
# regs[[2]] <- felm(default~post*treat|facility_no,data=default_sample_sum[default_sample_sum$type != "minitruck",])
# regs[[3]] <- felm(default~post*treat|facility_no,data=default_sample_sum)
# stargazer(regs,type = "text")
```


```{r univariate_new_default}
# univariate <- ddply(default_sample_sum,.(type,post),summarise,default=mean(default))
# univariate
```


```{r simulated_data,include=FALSE}
sim_data <- read.csv(file="E:/auto_strategicdefault/Processed/simulated_data.csv")
summary(felm(def_new~post*treat|0|0|loanid,data=sim_data))
summary(felm(def_cum~post*treat|loanid,data=sim_data))
ddply(sim_data,.(post,treat),summarise,def_new=mean(def_new))
ddply(sim_data,.(post,treat),summarise,def_cum=mean(def_cum))
```

